### ISSUE TITLE
bbox schema test is outdated

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ets-ogcapi-features10#223]
**Describe the bug**
The [test of the schema of the `bbox` parameter](https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java#L119-L125) is outdated.

The current test requires 

```yaml
  type: array
  minItems: 4
  maxItems: 6
  items:
    type: number
```

but in version 1.0.1 this was updated to 

```yaml
  type: array
  oneOf:
  - minItems: 4
    maxItems: 4
  - minItems: 6
    maxItems: 6
  items:
    type: number
```

See https://docs.ogc.org/is/17-069r4/17-069r4.html#_parameter_bbox (vs https://docs.ogc.org/is/17-069r3/17-069r3.html#_parameter_bbox).

To support implementations of versions 1.0.0 and 1.0.1, the test should accept both variants.

**To Reproduce**
Review code and standard.

**Expected behavior**
Both schemas should be accepted by the tests.

**Screenshots**
n/a

**Additional context**
n/a
